### ISSUE TITLE
Update worms taxa match with species list from Enrique

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/bio_mobilization_workshop#23]
File: [coverconcepcionspecies_matched.txt](https://github.com/ioos/bio_mobilization_workshop/files/8206839/coverconcepcionspecies_matched.txt)

Section on website: https://github.com/ioos/bio_mobilization_workshop/blob/965dfd9b7645170cc27266e64b3dd53364f1ae27/_episodes/03-data-cleaning.md?plain=1#L305-L332

**Comment by MathewBiddle** [comment]
Note that this is the output from WoRMS (already matched taxa) and we can use the spp list in the first column (ScientificName) for the test.

**Comment by MathewBiddle** [comment]
Should be fixed. See https://ioos.github.io/bio_mobilization_workshop/03-data-cleaning/index.html#matching-your-scientific-names-to-worms

might need to give it a minute to rebuild the site.

**Comment by albenson-usgs** [comment]
I feel like we lost some of the content that was available with the screenshots before. For instance, we lost the non-matching names (I don't think using "Scientific Name" works well here) and the ability to show a match in the dropdown in addition to an ambiguous match before it's selected. When you were asking for a file in the call yesterday I thought it was because you were going to demonstrate during the workshop the process for uploading the file live for the participants. I guess I didn't understand that it was to trade out all the screenshots.

**Comment by albenson-usgs** [comment]
I also wonder if we should show just pulling back the information you actually need so maybe only selecting LSID, accepted name, and classification?

**Comment by MathewBiddle** [comment]
so, should we revert those changes? 

All I want to show is that sometimes a person needs to be in the loop and make a decision. I think both get that point across. If you prefer the previous screenshots, we can revert the changes.

Here are the previous screenshots:
![](https://github.com/ioos/bio_mobilization_workshop/raw/f3ce748e3cae826e70b01ef76e843aff5eecfd68/fig/WoRMS_TaxonMatch_Preview.PNG)

![](https://github.com/ioos/bio_mobilization_workshop/raw/f3ce748e3cae826e70b01ef76e843aff5eecfd68/fig/WoRMS_TaxonMatch_MatchOutput.PNG)

**Comment by MathewBiddle** [comment]
@albenson-usgs, I think I misunderstood. I'll put the old screenshots back in. Then, during the presentation, I can use the example file from @eqmh to demo using the tool.

**Comment by MathewBiddle** [comment]
closed with https://github.com/ioos/bio_mobilization_workshop/commit/38af8add99ae2392f4d190d9b63cb976767223a7

See https://ioos.github.io/bio_mobilization_workshop/03-data-cleaning/index.html
